name: tracker_two
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  csv: ^5.0.2
  package_info_plus: ^5.0.1

  # ✅ Hive packages
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # ✅ Required for code generation
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
